apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lmbdnz-cyclenet
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi