apiVersion: batch/v1
kind: Job
metadata:
  name: cyclenet-data
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: cyclenet-container
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu: 1
        securityContext:
          runAsUser: 0
        command: ["/bin/bash", "-c", "cd /mnt/project && ./download-data.sh"]
        volumeMounts:
        - name: lmbdnz-cyclenet
          mountPath: /mnt/project
      volumes:
      - name: lmbdnz-cyclenet
        persistentVolumeClaim:
          claimName: lmbdnz-cyclenet
      restartPolicy: Never
  