apiVersion: batch/v1
kind: Job
metadata:
  name: cyclenet-train-a40
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cyclenet-container
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
        resources:
          requests:
            cpu: "4"
            memory: "48Gi"
            nvidia.com/a40: 1
          limits:
            cpu: "4"
            memory: "48Gi"
            nvidia.com/a40: 1
        securityContext:
          runAsUser: 0
        command: ["/bin/bash", "-c"]
        args:
          - >-
            source /opt/conda/etc/profile.d/conda.sh &&
            conda activate /mnt/project/envs/cycle &&
            cd /mnt/project/CycleNet &&
            python -u train.py
        volumeMounts:
        - name: lmbdnz-cyclenet
          mountPath: /mnt/project
      volumes:
      - name: lmbdnz-cyclenet
        persistentVolumeClaim:
          claimName: lmbdnz-cyclenet